apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-portal-frontend-$ENVIRONMENT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-portal-frontend-$ENVIRONMENT
      tier: budget-portal-frontend-$ENVIRONMENT
  template:
    metadata:
      labels:
        app: budget-portal-frontend-$ENVIRONMENT
        tier: budget-portal-frontend-$ENVIRONMENT
    spec:
      containers:
        - name: budget-portal-frontend
          image: kwalit/budget-portal-frontend:$TAG
          imagePullPolicy: Always
          env:
          - name: API_HOST
            value: "http://172.16.100.72:$PORT"
          - name: API_VERSION
            value: "v1"
          - name: TENANT_HOST
            value: "172.16.100.72"
          - name: ENVIRONMENT
            value: "$ENVIRONMENT"
          - name: CHATBOT_CONVERSATION_ENDPOINT
            value: "$CHATBOT_CONVERSATION_ENDPOINT"
          - name: CHATBOT_SYNC_ENDPOINT
            value: "$CHATBOT_SYNC_ENDPOINT"
      imagePullSecrets:
        - name: docker-registry-key
---
apiVersion: v1
kind: Service
metadata:
    name: budget-portal-frontend-$ENVIRONMENT
spec:
    selector:
        app: budget-portal-frontend-$ENVIRONMENT
    ports:
        - protocol: "TCP"
          port: 80
          targetPort: 80
    type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: budget-portal-frontend-$ENVIRONMENT
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: budget-portal-frontend-$ENVIRONMENT
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
