apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service-dev
  name: zookeeper-service-dev
spec:
  type: NodePort
  ports:
    - name: zookeeper-port-dev
      port: 2181
      nodePort: 30179
      targetPort: 2181
  selector:
    app: zookeeper-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-dev
  name: zookeeper-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-dev
  template:
    metadata:
      labels:
        app: zookeeper-dev
    spec:
      containers:
        - image: bitnami/zookeeper:latest
          imagePullPolicy: IfNotPresent
          name: zookeeper-dev
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
