apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker-dev
  name: kafka-service-dev
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker-dev
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker-dev
  name: kafka-broker-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-dev
  template:
    metadata:
      labels:
        app: kafka-broker-dev
    spec:
      hostname: kafka-broker-dev
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.97.145.212:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://queue-dev.redivu.com:80
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
