apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-$ENVIRONMENT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-$ENVIRONMENT
  template:
    metadata:
      labels:
        app: kafka-$ENVIRONMENT
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - name: zookeeper
              containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - name: kafka
              containerPort: 9092
          env:
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "kafka:9092"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          readinessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-$ENVIRONMENT
spec:
    selector:
        app: kafka-$ENVIRONMENT
    ports:
        - protocol: "TCP"
          port: 9092
          targetPort: kafka
    type: LoadBalancer
