version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: ksc-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: ksc-data
