apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksc-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksc-frontend-dev
      tier: ksc-frontend-dev
  template:
    metadata: 
      labels:
        app: ksc-frontend-dev
        tier: ksc-frontend-dev
    spec: 
      containers:
        - name: ksc-frontend
          image: kwalit/ksc-frontend:v22.8.3-dev
          imagePullPolicy: Always
          env:
          - name: API_HOST
            value: "http://172.31.65.106"
          - name: API_PORT
            value: "32680"
          - name: API_VERSION
            value: "v1"
          - name: TENANT_HOST
            value: "172.31.66.100" 
      imagePullSecrets:
        - name: my-registry-key
---
apiVersion: v1
kind: Service
metadata:
    name: ksc-frontend-dev
spec:
    selector:
        app: ksc-frontend-dev
    ports:
        - protocol: "TCP"
          port: 80
          targetPort: 80
    type: LoadBalancer
