apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksc-frontend-release
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ksc-frontend-release
      tier: ksc-frontend-release
  template:
    metadata: 
      labels:
        app: ksc-frontend-release
        tier: ksc-frontend-release
    spec: 
      containers:
        - name: ksc-frontend
          image: kwalit/ksc-frontend:v1.0.3-release
          env:
          - name: API_HOST
            value: "http://172.31.66.100"
          - name: API_PORT
            value: "3003"
          - name: API_VERSION
            value: "v1"
          - name: TENANT_HOST
            value: "172.31.66.100" 
      imagePullSecrets:
        - name: my-registry-key
---
apiVersion: v1
kind: Service
metadata:
    name: ksc-frontend-release
spec:
    selector:
        app: ksc-frontend-release
    ports:
        - protocol: "TCP"
          port: 80
          targetPort: 80
    type: LoadBalancer
