apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksc-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksc-frontend
      tier: frontend
  template:
    metadata: 
      labels:
        app: ksc-frontend
        tier: frontend
    spec: 
      containers:
        - name: ksc-frontend
          image: kwalit/ksc-frontend:latest
      imagePullSecrets:
        - name: my-registry-key
