apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksc-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksc-frontend
      tier: frontend
  template:
    metadata: 
      labels:
        app: ksc-frontend
        tier: frontend
    spec: 
      containers:
        - name: ksc-frontend
          image: kwalit/ksc-frontend:latest
          env:
          - name: API_HOST
            value: "http://172.20.66.100"
          - name: API_PORT
            value: "3000"
          - name: API_VERSION
            value: "v1"
          - name: TENANT_HOST
            value: "172.20.66.100" 
      imagePullSecrets:
        - name: my-registry-key
---
apiVersion: v1
kind: Service
metadata:
    name: ksc-frontend
spec:
    selector:
        app: ksc-frontend
    ports:
        - protocol: "TCP"
          port: 4200
          targetPort: 4200
    type: LoadBalancer
